### ISSUE TITLE
Secure authorization issue

### ISSUE THREAD

**Issue by MaxBQb** [AlluSoN/Bot_Mc_discord#23] opened 2021-12-25 08:31 UTC
During play session, we've got a bug with server multi-instance.
Log file has blocked by other process, so no reading available, 
which also leads to unauthorized access available.

Can you check file availability before start reading?
Or what the are other things you can do about that?

**Comment by Druzai** [comment] 2021-12-25 09:41
Maybe it was caused because that running server's CPU frequency was low, so bot's process was freezed for several seconds by starting Minecraft server instance.

Over all I can't reproduce it.

Closing this for now.

**Closed as completed by Druzai** 2021-12-25 09:41 UTC
Labels: bug
